;**********************************************************************************************
;										CONFIGURATION BITS
;**********************************************************************************************
	CONFIG	OSC=HS,FSCM=OFF,IESO=ON
	CONFIG	PWRT=ON,BOR=OFF,BORV=42
	CONFIG	WDT=OFF
	CONFIG	MCLRE=ON,PBAD=DIG,CCP2MX=C1
	CONFIG	STVR=ON,LVP=OFF,DEBUG=OFF
	CONFIG	CP0=OFF,CP1=OFF,CP2=OFF,CP3=OFF
	CONFIG	CPB=ON,CPD=OFF
	CONFIG	WRT0=OFF,WRT1=OFF,WRT2=OFF,WRT3=OFF
	CONFIG	WRTC=OFF,WRTB=ON,WRTD=OFF
	CONFIG	EBTR0=OFF,EBTR1=OFF,EBTR2=OFF,EBTR3=OFF
	CONFIG	EBTRB=ON
